==2664== Memcheck, a memory error detector
==2664== Copyright (C) 2002-2010, and GNU GPL'd, by Julian Seward et al.
==2664== Using Valgrind-3.6.1-Debian and LibVEX; rerun with -h for copyright info
==2664== Command: /home/jturney/psi4/objdir/bin/psi4
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x86ad020 is 288 bytes inside a block of size 568 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x6FF3714: fclose@@GLIBC_2.2.5 (iofclose.c:88)
==2664==    by 0x64763D7: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x86ad020 is 288 bytes inside a block of size 568 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x6FF3714: fclose@@GLIBC_2.2.5 (iofclose.c:88)
==2664==    by 0x64763D7: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x86ae020 is 0 bytes inside a block of size 32 free'd
==2664==    at 0x4C29097: realloc (vg_replace_malloc.c:525)
==2664==    by 0x63E6166: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E9927: PyList_Append (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647A7C5: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647A1F8: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6479C84: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647A173: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C577: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C65B: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6476314: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x86af020 is 448 bytes inside a block of size 576 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63E6464: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C59C: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C65B: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6476314: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x874d020 is 8,384 bytes inside a block of size 10,190 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x647C668: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6476314: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x874d020 is 8,384 bytes inside a block of size 10,190 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x647C668: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6476314: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x874e020 is 352 bytes inside a block of size 368 free'd
==2664==    at 0x4C29097: realloc (vg_replace_malloc.c:525)
==2664==    by 0x63E6166: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E9927: PyList_Append (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647A7C5: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6479C84: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647A187: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6479C84: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647A173: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6479C84: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647A173: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C577: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C65B: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x876b020 is 0 bytes after a block of size 32 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63E6464: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E6459: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x641DF99: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x641E06E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x641BB87: PyType_Ready (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x641F629: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6416397: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D6F4: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCABC: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCAD4: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB66A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8685020 is 1,536 bytes inside a block of size 1,864 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63E6464: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C59C: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C65B: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6476314: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x87b2020 is 272 bytes inside a block of size 280 free'd
==2664==    at 0x4C29097: realloc (vg_replace_malloc.c:525)
==2664==    by 0x63E6166: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E9927: PyList_Append (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647A7C5: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6479C84: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647A173: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C577: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647C65B: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6476314: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCCEB: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64968B8: _PyObject_GC_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1148: PyFrame_New (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E00D: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCCFF: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64968B8: _PyObject_GC_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1148: PyFrame_New (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E00D: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64968B8: _PyObject_GC_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1148: PyFrame_New (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E00D: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8812020 is 160 bytes inside a block of size 2,048 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63E6464: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E01F1: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E088: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64058FE: _PyString_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640B4A6: PyString_Repr (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F939F: PyObject_Repr (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E42BF: PyInt_FromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B755F: PyNumber_Int (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E4677: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6416712: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645BC6C: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8833020 is 336 bytes inside a block of size 908 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x645C78F: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64058FE: _PyString_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640BDDE: PyString_FromFormatV (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646EA0E: PyErr_Format (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E42F9: PyInt_FromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B755F: PyNumber_Int (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E4677: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6416712: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645BC6C: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8833020 is 336 bytes inside a block of size 908 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x645C78F: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E4339: PyInt_FromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B755F: PyNumber_Int (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E4677: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6416712: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645BC6C: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8833020 is 336 bytes inside a block of size 908 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x645C78F: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63D197A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63D19CF: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F6417: PyDict_SetItemString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645B7D7: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8834020 is 112 bytes inside a block of size 297 free'd
==2664==    at 0x4C29097: realloc (vg_replace_malloc.c:525)
==2664==    by 0x64058FE: _PyString_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640BDDE: PyString_FromFormatV (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646EA0E: PyErr_Format (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E42F9: PyInt_FromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B755F: PyNumber_Int (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E4677: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6416712: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645BC6C: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645C78F: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x888b020 is 272 bytes inside a block of size 1,104 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x64ED8EE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D6F4: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E6459: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E01F1: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EBE9: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8822020 is 2,000 bytes inside a block of size 3,696 free'd
==2664==    at 0x4C29097: realloc (vg_replace_malloc.c:525)
==2664==    by 0x63E6166: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E9927: PyList_Append (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63DA449: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D6F4: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCABC: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD17A: PyGrammar_AddAccelerators (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADDC4: PyParser_New (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE2B2: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCAD4: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD17A: PyGrammar_AddAccelerators (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADDC4: PyParser_New (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE2B2: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD17A: PyGrammar_AddAccelerators (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADDC4: PyParser_New (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE2B2: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8c5c020 is 240 bytes inside a block of size 676 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63AD17A: PyGrammar_AddAccelerators (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADDC4: PyParser_New (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE2B2: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCCEB: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADAA4: PyNode_AddChild (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADF65: PyParser_AddToken (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE389: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCCFF: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADAA4: PyNode_AddChild (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADF65: PyParser_AddToken (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE389: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD80B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD7D6: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD7D6: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD7D6: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADB8D: PyNode_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648125D: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbb020 is 34,272 bytes inside a block of size 36,032 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63AE4B7: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD835: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADB8D: PyNode_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648125D: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbb020 is 34,272 bytes inside a block of size 36,032 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63AE4B7: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD8F8: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADB8D: PyNode_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648125D: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbb020 is 34,272 bytes inside a block of size 36,032 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63AE4B7: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645FB71: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6462A6B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6464686: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64633CE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646414E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6464262: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6463407: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6467E3C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646A68F: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C6C9: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbd020 is 208 bytes inside a block of size 768 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6484E72: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64874B1: PySymtable_Build (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C3BB: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645FB71: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646279C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6463407: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6463407: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6467E3C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646A68F: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C6C9: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbd020 is 208 bytes inside a block of size 768 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6484E72: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64874B1: PySymtable_Build (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C3BB: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64058FE: _PyString_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6461A1F: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C525: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbf020 is 0 bytes after a block of size 384 alloc'd
==2664==    at 0x4C28F9F: malloc (vg_replace_malloc.c:236)
==2664==    by 0x645FBA0: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64617CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C525: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6461FB5: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C525: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbf020 is 0 bytes after a block of size 384 alloc'd
==2664==    at 0x4C28F9F: malloc (vg_replace_malloc.c:236)
==2664==    by 0x645FBA0: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64617CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C525: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645F268: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C537: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbd020 is 208 bytes inside a block of size 768 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6484E72: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64874B1: PySymtable_Build (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C3BB: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C537: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645F041: PyEval_EvalCode (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbd020 is 208 bytes inside a block of size 768 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6484E72: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64874B1: PySymtable_Build (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C3BB: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648150A: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645F041: PyEval_EvalCode (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8cbf020 is 0 bytes after a block of size 384 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x645F268: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C537: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6459A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E0446: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EBE9: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645F041: PyEval_EvalCode (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6475EA1: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8c59020 is 7,632 bytes inside a block of size 8,192 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63DAD41: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63DAE32: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63D174C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6458AC5: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCCEB: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64968B8: _PyObject_GC_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1148: PyFrame_New (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E723: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1A1B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA364B3: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCCFF: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64968B8: _PyObject_GC_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1148: PyFrame_New (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E723: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1A1B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA364B3: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E6459: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64ED371: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64ED460: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D6F4: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1A1B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8ed4020 is 896 bytes inside a block of size 1,104 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x64ECBE8: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64ED460: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D6F4: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1A1B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA364B3: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8f01020 is 2,832 bytes inside a block of size 3,061 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x647C668: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6476314: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645A5F0: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64058FE: _PyString_Resize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ACDC2: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D35F: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1A1B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64ECE63: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64ED460: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D6F4: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8f28020 is 832 bytes inside a block of size 1,104 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x64ED02C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64ED460: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D6F4: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1A1B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64ECE63: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64ED460: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6458B55: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1A1B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA364B3: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8ed4020 is 896 bytes inside a block of size 1,104 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x64ECBE8: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64ED460: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D6F4: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1A1B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA364B3: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA3655F: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f61020 is 1,808 bytes inside a block of size 2,048 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63E6464: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E01F1: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E088: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645E063: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645D074: PyEval_EvalFrameEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645EF04: PyEval_EvalCodeEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADAA4: PyNode_AddChild (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE183: PyParser_AddToken (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE389: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f6f020 is 464 bytes inside a block of size 960 free'd
==2664==    at 0x4C29097: realloc (vg_replace_malloc.c:525)
==2664==    by 0x63ADAA4: PyNode_AddChild (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADF65: PyParser_AddToken (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE389: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD8F8: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD7D6: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD7D6: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADB8D: PyNode_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648125D: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f6f020 is 464 bytes inside a block of size 960 free'd
==2664==    at 0x4C29097: realloc (vg_replace_malloc.c:525)
==2664==    by 0x63ADAA4: PyNode_AddChild (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADF65: PyParser_AddToken (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE389: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD956: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADB8D: PyNode_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648125D: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f6f020 is 464 bytes inside a block of size 960 free'd
==2664==    at 0x4C29097: realloc (vg_replace_malloc.c:525)
==2664==    by 0x63ADAA4: PyNode_AddChild (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63ADF65: PyParser_AddToken (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AE389: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64812A2: PyParser_ASTFromString (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x648148B: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645FB71: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6468AA5: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646A68F: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C6C9: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f71020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCCE2: PyObject_Realloc (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x645FB71: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646279C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646414E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64633CE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646748A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646A68F: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C6C9: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f71020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C537: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f71020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB66A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6457806: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x903b020 is 32 bytes inside a block of size 1,000 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63B91F2: PyObject_Call (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCABC: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCAD4: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647620C: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647739B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647761E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6477C4E: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6478269: PyImport_ImportModuleLevel (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6455AAE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
	RKS  0 1   B97 Energy.............................................PASSED
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA37D62: boost::python::api::object_base::~object_base() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA37C6B: boost::python::api::object::~object() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA3811B: boost::python::detail::str_base::~str_base() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA38135: boost::python::str::~str() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA369D8: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f62020 is 0 bytes inside a block of size 56 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x1ABDB12: psi::Matrix::free(double**) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1ABF5EA: psi::Matrix::release() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1ABD9C7: psi::Matrix::~Matrix() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xAE0654: void boost::checked_delete<psi::Matrix>(psi::Matrix*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xAEBB3F: boost::detail::sp_counted_impl_p<psi::Matrix>::dispose() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA08303: boost::detail::sp_counted_base::release() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA0837C: boost::detail::shared_count::~shared_count() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA3766B: boost::shared_ptr<psi::Matrix>::~shared_ptr() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDBA6D2: psi::scf::RKSPotential::USO2AO(boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Dimension>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDB7B3A: psi::scf::RKSPotential::buildPotential(boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Dimension>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83AF0: psi::scf::RKS::form_V() (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
	RKS  0 1   B97 Energy: computed value (-65.977694) does not match (-74.949341) to 3 digits.
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E03D9: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6489E1A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BBC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f77020 is 16 bytes before a block of size 406 alloc'd
==2664==    at 0x4C28F9F: malloc (vg_replace_malloc.c:236)
==2664==    by 0x6405F0C: PyString_FromStringAndSize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647ED85: PyCode_Optimize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6462350: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x646C525: PyAST_Compile (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64814A5: PyRun_StringFlags (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x23FBE95: boost::python::exec(boost::python::str, boost::python::api::object, boost::python::api::object) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA36701: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E03D9: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6489E1A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BBC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f77020 is 16 bytes before a block of size 406 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E03D9: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6489E1A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BBC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E03D9: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6489E1A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BBC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f19020 is 12 bytes after a block of size 4 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0xAAE14D: __gnu_cxx::new_allocator<int>::deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xAA6C69: std::_Vector_base<int, std::allocator<int> >::_M_deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xCC92E6: std::vector<int, std::allocator<int> >::_M_insert_aux(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, int const&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xCC90AB: std::vector<int, std::allocator<int> >::push_back(int const&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD9128D: void psi::TwoBodySOInt::compute_shell<psi::scf::J_K_Functor>(int, int, int, int, psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD8E7E0: void psi::TwoBodySOInt::compute_quartets<boost::shared_ptr<psi::SOShellCombinationsIterator>, psi::scf::J_K_Functor>(boost::shared_ptr<psi::SOShellCombinationsIterator>&, psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD8DEFB: void psi::TwoBodySOInt::compute_integrals<psi::scf::J_K_Functor>(psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD8CBAC: void psi::scf::HF::process_tei<psi::scf::J_K_Functor>(psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83E76: psi::scf::RKS::form_G() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BC1D: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xB709E0: psi::scf::scf(psi::Options&, _object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x9095020 is 592 bytes inside a block of size 2,251 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x9095020 is 592 bytes inside a block of size 2,251 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x9093020 is 1 bytes after a block of size 31 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0x69031E2: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16)
==2664==    by 0xDB8790: psi::scf::RKSPotential::buildPotential(boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Dimension>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83AF0: psi::scf::RKS::form_V() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83C51: psi::scf::RKS::form_G() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BC1D: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xB709E0: psi::scf::scf(psi::Options&, _object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA2FE2C: py_psi_scf_callbacks(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA56B93: _object* boost::python::detail::invoke<boost::python::to_python_value<double const&>, double (*)(_object*, _object*), boost::python::arg_from_python<_object*>, boost::python::arg_from_python<_object*> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<double const&> const&, double (*&)(_object*, _object*), boost::python::arg_from_python<_object*>&, boost::python::arg_from_python<_object*>&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA5182D: boost::python::detail::caller_arity<2u>::impl<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA4ED04: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> > >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x2400A20: boost::python::objects::py_function::operator()(_object*, _object*) const (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6BA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x9092020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8d2b020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8d5a020 is 416 bytes inside a block of size 816 free'd
==2664==    at 0x4C27C6E: operator delete[](void*) (vg_replace_malloc.c:409)
==2664==    by 0x1AC627B: psi::Matrix::power(double, double) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x23E9C47: psi::DIISManager::extrapolate(int, ...) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDA8CD4: psi::scf::RHF::diis() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BEB4: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xB709E0: psi::scf::scf(psi::Options&, _object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA2FE2C: py_psi_scf_callbacks(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA56B93: _object* boost::python::detail::invoke<boost::python::to_python_value<double const&>, double (*)(_object*, _object*), boost::python::arg_from_python<_object*>, boost::python::arg_from_python<_object*> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<double const&> const&, double (*&)(_object*, _object*), boost::python::arg_from_python<_object*>&, boost::python::arg_from_python<_object*>&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA5182D: boost::python::detail::caller_arity<2u>::impl<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA4ED04: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> > >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x2400A20: boost::python::objects::py_function::operator()(_object*, _object*) const (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x23FE8DD: boost::python::objects::function::call(_object*, _object*) const (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CCA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8d2b020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8d2b020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8676020 is 3,760 bytes inside a block of size 4,096 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0xAAE14D: __gnu_cxx::new_allocator<int>::deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xAA6C69: std::_Vector_base<int, std::allocator<int> >::_M_deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xCC92E6: std::vector<int, std::allocator<int> >::_M_insert_aux(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, int const&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xCC90AB: std::vector<int, std::allocator<int> >::push_back(int const&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A7E691: psi::OctreeGridBlocker::block() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A582E0: psi::MolecularGrid::block(int, int) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A5C020: psi::MolecularGrid::buildGrid(std::vector<boost::shared_ptr<psi::AtomicGrid>, std::allocator<boost::shared_ptr<psi::AtomicGrid> > >&, std::string const&, boost::shared_ptr<psi::BasisExtents>, int, int) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A545B7: psi::DFTGrid::buildGridFromOptions() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A5240E: psi::DFTGrid::DFTGrid(boost::shared_ptr<psi::Molecule>, boost::shared_ptr<psi::BasisSet>, psi::Options&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDB71D6: psi::scf::KSPotential::buildGrid() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDB70F6: psi::scf::KSPotential::common_init() (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6DA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8676020 is 3,760 bytes inside a block of size 4,096 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0xAAE14D: __gnu_cxx::new_allocator<int>::deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xAA6C69: std::_Vector_base<int, std::allocator<int> >::_M_deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xCC92E6: std::vector<int, std::allocator<int> >::_M_insert_aux(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, int const&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xCC90AB: std::vector<int, std::allocator<int> >::push_back(int const&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A7E691: psi::OctreeGridBlocker::block() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A582E0: psi::MolecularGrid::block(int, int) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A5C020: psi::MolecularGrid::buildGrid(std::vector<boost::shared_ptr<psi::AtomicGrid>, std::allocator<boost::shared_ptr<psi::AtomicGrid> > >&, std::string const&, boost::shared_ptr<psi::BasisExtents>, int, int) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A545B7: psi::DFTGrid::buildGridFromOptions() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1A5240E: psi::DFTGrid::DFTGrid(boost::shared_ptr<psi::Molecule>, boost::shared_ptr<psi::BasisSet>, psi::Options&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDB71D6: psi::scf::KSPotential::buildGrid() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDB70F6: psi::scf::KSPotential::common_init() (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8833020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCABC: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCAD4: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB66A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x99ad020 is 0 bytes after a block of size 608 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x640F91B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB6BA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CCA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x9039020 is 8 bytes after a block of size 8 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0xAAE14D: __gnu_cxx::new_allocator<int>::deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xAA6C69: std::_Vector_base<int, std::allocator<int> >::_M_deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xCC92E6: std::vector<int, std::allocator<int> >::_M_insert_aux(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, int const&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xCC90AB: std::vector<int, std::allocator<int> >::push_back(int const&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD9125B: void psi::TwoBodySOInt::compute_shell<psi::scf::J_K_Functor>(int, int, int, int, psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD8E7E0: void psi::TwoBodySOInt::compute_quartets<boost::shared_ptr<psi::SOShellCombinationsIterator>, psi::scf::J_K_Functor>(boost::shared_ptr<psi::SOShellCombinationsIterator>&, psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD8DEFB: void psi::TwoBodySOInt::compute_integrals<psi::scf::J_K_Functor>(psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD8CBAC: void psi::scf::HF::process_tei<psi::scf::J_K_Functor>(psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83E76: psi::scf::RKS::form_G() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BC1D: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xB709E0: psi::scf::scf(psi::Options&, _object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCABC: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCAD4: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB65A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8fb4020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CCA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8fb4020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64E6A6A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8f1c020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCABC: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64E6A6A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCAD4: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64E6A6A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCABC: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCAD4: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCABC: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCAD4: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8EFA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756CC: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f01020 is 0 bytes inside a block of size 8 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0xAAE14D: __gnu_cxx::new_allocator<int>::deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xAA6C69: std::_Vector_base<int, std::allocator<int> >::_M_deallocate(int*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA98AA4: std::_Vector_base<int, std::allocator<int> >::~_Vector_base() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xC191A7: std::vector<int, std::allocator<int> >::~vector() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD91959: void psi::TwoBodySOInt::compute_shell<psi::scf::J_K_Functor>(int, int, int, int, psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD8E7E0: void psi::TwoBodySOInt::compute_quartets<boost::shared_ptr<psi::SOShellCombinationsIterator>, psi::scf::J_K_Functor>(boost::shared_ptr<psi::SOShellCombinationsIterator>&, psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD8DEFB: void psi::TwoBodySOInt::compute_integrals<psi::scf::J_K_Functor>(psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD8CBAC: void psi::scf::HF::process_tei<psi::scf::J_K_Functor>(psi::scf::J_K_Functor&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83E76: psi::scf::RKS::form_G() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BC1D: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xB709E0: psi::scf::scf(psi::Options&, _object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CAA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x87b4020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x87b5020 is 16 bytes inside a block of size 30 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0x69031E2: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16)
==2664==    by 0xDB821B: psi::scf::RKSPotential::buildPotential(boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Dimension>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83AF0: psi::scf::RKS::form_V() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83C51: psi::scf::RKS::form_G() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BC1D: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xB709E0: psi::scf::scf(psi::Options&, _object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA2FE2C: py_psi_scf_callbacks(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA56B93: _object* boost::python::detail::invoke<boost::python::to_python_value<double const&>, double (*)(_object*, _object*), boost::python::arg_from_python<_object*>, boost::python::arg_from_python<_object*> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<double const&> const&, double (*&)(_object*, _object*), boost::python::arg_from_python<_object*>&, boost::python::arg_from_python<_object*>&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA5182D: boost::python::detail::caller_arity<2u>::impl<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA4ED04: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> > >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x2400A20: boost::python::objects::py_function::operator()(_object*, _object*) const (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Conditional jump or move depends on uninitialised value(s)
==2664==    at 0x63FCABC: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Use of uninitialised value of size 8
==2664==    at 0x63FCAD4: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63CB635: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CBA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x8809020 is 1,968 bytes inside a block of size 3,072 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x87c2020 is 32 bytes inside a block of size 33 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0x69031E2: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16)
==2664==    by 0x1927EEC: psi::functional::B_X_Functional::computeRKSFunctional(boost::shared_ptr<psi::RKSFunctions>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x15F78AD: psi::functional::SuperFunctional::computeRKSFunctional(boost::shared_ptr<psi::RKSFunctions>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDB803A: psi::scf::RKSPotential::buildPotential(boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Dimension>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83AF0: psi::scf::RKS::form_V() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83C51: psi::scf::RKS::form_G() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BC1D: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xB709E0: psi::scf::scf(psi::Options&, _object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA2FE2C: py_psi_scf_callbacks(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA56B93: _object* boost::python::detail::invoke<boost::python::to_python_value<double const&>, double (*)(_object*, _object*), boost::python::arg_from_python<_object*>, boost::python::arg_from_python<_object*> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<double const&> const&, double (*&)(_object*, _object*), boost::python::arg_from_python<_object*>&, boost::python::arg_from_python<_object*>&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA5182D: boost::python::detail::caller_arity<2u>::impl<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63E1CAA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64758A5: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x879a020 is 16 bytes before a block of size 40 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0x23ED237: __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<int const, bool> > >::deallocate(std::_Rb_tree_node<std::pair<int const, bool> >*, unsigned long) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x23ED05B: std::_Rb_tree<int, std::pair<int const, bool>, std::_Select1st<std::pair<int const, bool> >, std::less<int>, std::allocator<std::pair<int const, bool> > >::_M_put_node(std::_Rb_tree_node<std::pair<int const, bool> >*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x23EDFD6: std::_Rb_tree<int, std::pair<int const, bool>, std::_Select1st<std::pair<int const, bool> >, std::less<int>, std::allocator<std::pair<int const, bool> > >::_M_destroy_node(std::_Rb_tree_node<std::pair<int const, bool> >*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x23EDEEE: std::_Rb_tree<int, std::pair<int const, bool>, std::_Select1st<std::pair<int const, bool> >, std::less<int>, std::allocator<std::pair<int const, bool> > >::_M_erase(std::_Rb_tree_node<std::pair<int const, bool> >*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x23EDE3A: std::_Rb_tree<int, std::pair<int const, bool>, std::_Select1st<std::pair<int const, bool> >, std::less<int>, std::allocator<std::pair<int const, bool> > >::~_Rb_tree() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x23EDDD9: std::map<int, bool, std::less<int>, std::allocator<std::pair<int const, bool> > >::~map() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x23EDD1F: psi::DIISEntry::~DIISEntry() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x23EAAB9: psi::DIISManager::~DIISManager() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD5F1D6: void boost::checked_delete<psi::DIISManager>(psi::DIISManager*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD62449: boost::detail::sp_counted_impl_p<psi::DIISManager>::dispose() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA08303: boost::detail::sp_counted_base::release() (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58BA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x640F902: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58BA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C9A3A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64758A5: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x86fc020 is 256 bytes inside a block of size 840 free'd
==2664==    at 0x4C27C6E: operator delete[](void*) (vg_replace_malloc.c:409)
==2664==    by 0x1AAF8C7: psi::IrreducibleRepresentation::init(int, int, char const*, char const*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1AAF68C: psi::IrreducibleRepresentation::~IrreducibleRepresentation() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1B3CAF9: psi::PetiteList::compute_aotoso_info() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1B69F73: psi::SOBasisSet::init() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1B69773: psi::SOBasisSet::SOBasisSet(boost::shared_ptr<psi::BasisSet> const&, psi::IntegralFactory const*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1B6CFEE: psi::OneBodySOInt::common_init() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1B6CE79: psi::OneBodySOInt::OneBodySOInt(boost::shared_ptr<psi::OneBodyAOInt> const&, psi::IntegralFactory const*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1B56FD1: psi::PotentialSOInt::PotentialSOInt(boost::shared_ptr<psi::OneBodyAOInt> const&, psi::IntegralFactory const*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0x1AA72BF: psi::IntegralFactory::so_potential(int) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD73B08: psi::scf::HF::form_H() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BAA5: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C9A3A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64758A5: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==  Address 0x876e020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C9A1B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64758A5: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x876f020 is 8 bytes after a block of size 280 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C58AA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63C9A3A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64758A5: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6415D8B: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8E8F: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647578B: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8809020 is 1,968 bytes inside a block of size 3,072 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647598F: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x85ff020 is 0 bytes inside a block of size 31 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0x69031E2: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16)
==2664==    by 0x1B41FE3: psi::RKSFunctions::computeProperties(boost::shared_ptr<psi::BlockOPoints>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDB7FD2: psi::scf::RKSPotential::buildPotential(boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Dimension>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83AF0: psi::scf::RKS::form_V() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83C51: psi::scf::RKS::form_G() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BC1D: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xB709E0: psi::scf::scf(psi::Options&, _object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA2FE2C: py_psi_scf_callbacks(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA56B93: _object* boost::python::detail::invoke<boost::python::to_python_value<double const&>, double (*)(_object*, _object*), boost::python::arg_from_python<_object*>, boost::python::arg_from_python<_object*> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<double const&> const&, double (*&)(_object*, _object*), boost::python::arg_from_python<_object*>&, boost::python::arg_from_python<_object*>&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA5182D: boost::python::detail::caller_arity<2u>::impl<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA4ED04: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> > >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64757EB: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8600020 is 64 bytes inside a block of size 280 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x647598F: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6475212: _PyImport_Fini (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AB4: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f02020 is 528 bytes inside a block of size 768 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8EFA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756CC: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6475212: _PyImport_Fini (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AB4: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8f02020 is 528 bytes inside a block of size 768 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35CA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8EFA: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756CC: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6475212: _PyImport_Fini (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AB4: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8685020 is 16 bytes before a block of size 30 free'd
==2664==    at 0x4C27FF2: operator delete(void*) (vg_replace_malloc.c:387)
==2664==    by 0x69031E2: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16)
==2664==    by 0x1B41CEB: psi::RKSFunctions::computeProperties(boost::shared_ptr<psi::BlockOPoints>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xDB7FD2: psi::scf::RKSPotential::buildPotential(boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Matrix>, boost::shared_ptr<psi::Dimension>) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83AF0: psi::scf::RKS::form_V() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD83C51: psi::scf::RKS::form_G() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xD7BC1D: psi::scf::HF::compute_energy() (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xB709E0: psi::scf::scf(psi::Options&, _object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA2FE2C: py_psi_scf_callbacks(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA56B93: _object* boost::python::detail::invoke<boost::python::to_python_value<double const&>, double (*)(_object*, _object*), boost::python::arg_from_python<_object*>, boost::python::arg_from_python<_object*> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<double const&> const&, double (*&)(_object*, _object*), boost::python::arg_from_python<_object*>&, boost::python::arg_from_python<_object*>&) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA5182D: boost::python::detail::caller_arity<2u>::impl<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA4ED04: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> > >::operator()(_object*, _object*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664== 
==2664== 
==2664== More than 100 errors detected.  Subsequent errors
==2664== will still be recorded, but in less detail than before.
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F410B: PyDict_Fini (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482B0E: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8811020 is 160 bytes inside a block of size 280 free'd
==2664==    at 0x4C282E0: free (vg_replace_malloc.c:366)
==2664==    by 0x63F35EC: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64E6A6A: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F35AE: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F2586: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F4CFD: PyDict_SetItem (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63F8DF5: _PyModule_Clear (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x64756B8: PyImport_Cleanup (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482AAA: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664== 
==2664== Invalid read of size 4
==2664==    at 0x63FCAB3: PyObject_Free (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x63AD3ED: PyGrammar_RemoveAccelerators (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6482B20: Py_Finalize (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481A97: Py_Exit (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481BC3: ??? (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0x6481E64: PyErr_PrintEx (in /usr/lib/libpython2.7.so.1.0)
==2664==    by 0xA36A4E: psi::Python::run(_IO_FILE*) (in /home/jturney/psi4/objdir/bin/psi4)
==2664==    by 0xA07F3F: main (in /home/jturney/psi4/objdir/bin/psi4)
==2664==  Address 0x8c5c020 is not stack'd, malloc'd or (recently) free'd
==2664== 
==2664== 
==2664== HEAP SUMMARY:
==2664==     in use at exit: 2,313,366 bytes in 1,562 blocks
==2664==   total heap usage: 84,735 allocs, 83,173 frees, 64,429,668 bytes allocated
==2664== 
==2664== LEAK SUMMARY:
==2664==    definitely lost: 0 bytes in 0 blocks
==2664==    indirectly lost: 0 bytes in 0 blocks
==2664==      possibly lost: 252,002 bytes in 469 blocks
==2664==    still reachable: 2,061,364 bytes in 1,093 blocks
==2664==         suppressed: 0 bytes in 0 blocks
==2664== Rerun with --leak-check=full to see details of leaked memory
==2664== 
==2664== For counts of detected and suppressed errors, rerun with: -v
==2664== Use --track-origins=yes to see where uninitialised values come from
==2664== ERROR SUMMARY: 1201 errors from 102 contexts (suppressed: 9 from 8)
